title: ZOTI
email: your-email@example.com
description: >- 
  A generic tool suite for describing code synthesis flows
# baseurl: "/zoti"
# url: "https://ericsson.github.io/" 
github_username:  "https://github.com/ugeorge"
#logo: [Location of the logo]
show_downloads: false

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Makefile

include:
  - _images
  - _static
  - _sphinx*
  - _sources
  - _modules
