title: ZOTI
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A generic tool suite for describing code synthesis flows
# baseurl: ""
url: "https://ericsson.github.io/zoti/" 
github_username:  ugeorge
#logo: [Location of the logo]
show_downloads: false

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Makefile

include:
  - _images
  - _static
  - _sphinx*
  - _sources
  - _modules
